swagger: '2.0'
info:
  description: This is the API documentation of the AMT Gamification project
  version: 1.0.0
  title: GamificationAPI
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /api
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /registration:
    get:
      responses:
        '200':
          description: list all registered applications
          schema:
            title: Registration summary
            type: array
            items:
              $ref: '#/definitions/RegistrationSummary'
    post:
      parameters:
        - name: registration
          in: body
          description: the info required to register an application
          schema:
            $ref: '#/definitions/Registration'
          required: true
      responses:
        '200':
          description: Register a new application
  /auth:
    post:
      operationId: authentificateApplicationAndGetToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: The info required to authentificate an application
          schema:
            $ref: "#/definitions/Credentials"
          required: true
      responses:
        200:
          description: Authentification Successful
          schema:
            $ref: "#definitions/Token"
        401:
          description: Authentification Failed
  /events:
    post:
      description: Report that a new event has happened in the gamified application
      operationId: reportEvent
      parameters:
        - $ref: "#/parameters/TokenHeader"
      produces:
        - application/json
      responses:
        202:
          description: The plateform has accepted the event and will process it
          schema:
            $ref: "#/definitions/Event"


      - name: registration
  /users/{id}:
    get:
      description: Retrieve one user by id
      operationId: findUserById
      parameters:
        - $ref: "#/parameters/TokenHeader"
        - name: id
          in: path
          description: id of the user to fetch
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Return the specified user state
          schema:
            $ref: "#/definitions/User"
definitions:
  RegistrationSummary:
    type: object
    properties:
      applicationName:
        type: string
  Registration:
    type: object
    properties:
      name:
        type: string
      password:
        type: string
  Credentials:
    type: object
      properties:
        name:
          type: string
        password:
          type: string
  Event:
    type: object
      properties:
        type:
          type: string
        userId:
          type: string
        timestamp:
          type: date-time
        properties:
          type: object
  Token:
    type: object
      properties:
        appllicationName:
          type: string
  User:
    type: object
      properties:
        userId:
          type: string
        numberOfEvents:
          type: string
  Parameters:
    TokenHeader:
      description: token that identifies the application sending the request
      name: x-gamification-token
      in: header
      required: true
      type: string




