version: '3.1'
services:
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=AMT_WP2
     - MYSQL_USER=amt
     - MYSQL_PASSWORD=amt
    ports:
     - "3306:3306"
  adminer:
    build: ./adminer
    restart: always
    ports:
     - "6060:8080"
    links:
     - mysql:db
    depends_on:
     - mysql