/*
 * GamificationAPI
 * This is the API documentation of the AMT Gamification project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EventHashMap
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-08T21:07:52.128+01:00")
public class EventHashMap {
  @SerializedName("code")
  private String code = null;

  @SerializedName("text")
  private String text = null;

  public EventHashMap code(String code) {
    this.code = code;
    return this;
  }

   /**
   * ID
   * @return code
  **/
  @ApiModelProperty(value = "ID")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EventHashMap text(String text) {
    this.text = text;
    return this;
  }

   /**
   * content
   * @return text
  **/
  @ApiModelProperty(value = "content")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventHashMap eventHashMap = (EventHashMap) o;
    return Objects.equals(this.code, eventHashMap.code) &&
        Objects.equals(this.text, eventHashMap.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventHashMap {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

