/*
 * GamificationAPI
 * This is the API documentation of the AMT Gamification project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * How many points an user has on a given point scale
 */
@ApiModel(description = "How many points an user has on a given point scale")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-08T21:07:52.128+01:00")
public class PointsOnPointScale {
  @SerializedName("pointScaleId")
  private BigDecimal pointScaleId = null;

  @SerializedName("points")
  private BigDecimal points = null;

  public PointsOnPointScale pointScaleId(BigDecimal pointScaleId) {
    this.pointScaleId = pointScaleId;
    return this;
  }

   /**
   * The point scale
   * @return pointScaleId
  **/
  @ApiModelProperty(value = "The point scale")
  public BigDecimal getPointScaleId() {
    return pointScaleId;
  }

  public void setPointScaleId(BigDecimal pointScaleId) {
    this.pointScaleId = pointScaleId;
  }

  public PointsOnPointScale points(BigDecimal points) {
    this.points = points;
    return this;
  }

   /**
   * How many points are on the point scale
   * @return points
  **/
  @ApiModelProperty(value = "How many points are on the point scale")
  public BigDecimal getPoints() {
    return points;
  }

  public void setPoints(BigDecimal points) {
    this.points = points;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointsOnPointScale pointsOnPointScale = (PointsOnPointScale) o;
    return Objects.equals(this.pointScaleId, pointsOnPointScale.pointScaleId) &&
        Objects.equals(this.points, pointsOnPointScale.points);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointScaleId, points);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointsOnPointScale {\n");
    
    sb.append("    pointScaleId: ").append(toIndentedString(pointScaleId)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

