/*
 * AMT
 * Gamification App
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.heig.amt.gamification.tests.model;

import java.util.Objects;
import ch.heig.amt.gamification.tests.model.BadgeDTO;
import ch.heig.amt.gamification.tests.model.UserDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BadgesResponseDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-20T17:27:44.724+01:00")
public class BadgesResponseDTO {
  @SerializedName("badge")
  private BadgeDTO badge = null;

  @SerializedName("user")
  private UserDTO user = null;

  @SerializedName("appName")
  private String appName = null;

  public BadgesResponseDTO badge(BadgeDTO badge) {
    this.badge = badge;
    return this;
  }

   /**
   * Get badge
   * @return badge
  **/
  @ApiModelProperty(value = "")
  public BadgeDTO getBadge() {
    return badge;
  }

  public void setBadge(BadgeDTO badge) {
    this.badge = badge;
  }

  public BadgesResponseDTO user(UserDTO user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public UserDTO getUser() {
    return user;
  }

  public void setUser(UserDTO user) {
    this.user = user;
  }

  public BadgesResponseDTO appName(String appName) {
    this.appName = appName;
    return this;
  }

   /**
   * Get appName
   * @return appName
  **/
  @ApiModelProperty(value = "")
  public String getAppName() {
    return appName;
  }

  public void setAppName(String appName) {
    this.appName = appName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BadgesResponseDTO badgesResponseDTO = (BadgesResponseDTO) o;
    return Objects.equals(this.badge, badgesResponseDTO.badge) &&
        Objects.equals(this.user, badgesResponseDTO.user) &&
        Objects.equals(this.appName, badgesResponseDTO.appName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(badge, user, appName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BadgesResponseDTO {\n");
    
    sb.append("    badge: ").append(toIndentedString(badge)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

