/*
 * AMT
 * Gamification App
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.heig.amt.gamification.tests.model;

import java.util.Objects;
import ch.heig.amt.gamification.tests.model.BadgeDTO;
import ch.heig.amt.gamification.tests.model.PointScaleDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RuleResponseDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-21T16:10:19.911+01:00")
public class RuleResponseDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("badge")
  private BadgeDTO badge = null;

  @SerializedName("pointScale")
  private PointScaleDTO pointScale = null;

  public RuleResponseDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RuleResponseDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RuleResponseDTO type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RuleResponseDTO quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public RuleResponseDTO badge(BadgeDTO badge) {
    this.badge = badge;
    return this;
  }

   /**
   * Get badge
   * @return badge
  **/
  @ApiModelProperty(value = "")
  public BadgeDTO getBadge() {
    return badge;
  }

  public void setBadge(BadgeDTO badge) {
    this.badge = badge;
  }

  public RuleResponseDTO pointScale(PointScaleDTO pointScale) {
    this.pointScale = pointScale;
    return this;
  }

   /**
   * Get pointScale
   * @return pointScale
  **/
  @ApiModelProperty(value = "")
  public PointScaleDTO getPointScale() {
    return pointScale;
  }

  public void setPointScale(PointScaleDTO pointScale) {
    this.pointScale = pointScale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleResponseDTO ruleResponseDTO = (RuleResponseDTO) o;
    return Objects.equals(this.id, ruleResponseDTO.id) &&
        Objects.equals(this.name, ruleResponseDTO.name) &&
        Objects.equals(this.type, ruleResponseDTO.type) &&
        Objects.equals(this.quantity, ruleResponseDTO.quantity) &&
        Objects.equals(this.badge, ruleResponseDTO.badge) &&
        Objects.equals(this.pointScale, ruleResponseDTO.pointScale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, quantity, badge, pointScale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleResponseDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    badge: ").append(toIndentedString(badge)).append("\n");
    sb.append("    pointScale: ").append(toIndentedString(pointScale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

